# New ports collection makefile for:	py-solrpy
# Date created:		2011-07-15
# Whom:			Lukas Lalinsky <lalinsky@gmail.com>
#
# $FreeBSD$
#

PORTNAME=	solrpy
PORTVERSION=	0.9.4
CATEGORIES=	devel python
MASTER_SITES=	http://pypi.python.org/packages/source/s/solrpy/

PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	lalinsky@gmail.com
COMMENT=	Client for the Solr search service

USE_PYTHON=	yes
USE_PYDISTUTILS=	easy_install

PYDISTUTILS_EGGINFO=    solrpy-${PORTVERSION}-py${PYTHON_VER}.egg-info

.include <bsd.port.mk>
